var treeData = [

  {
    "idx" : 1,
    "name": "Berghaus",
    "year": "1841",
    "prcp": "0",
    "clr" : "goldenrod",
    "map" : true,
    "val" : false,
    "ant" : "unknown",
    "yoff": 0,  // not being used
  },

  {
    "idx" : 2,
    "name": "Johnston",
    "year": "1854",
    "prcp": "0",
    "clr" : "goldenrod",
    "map" : true,
    "val" : false,
    "ant" : "unknown",
    "yoff": 0,
  },
 
  {
    "idx" : 3,
    "name": "Wojeikof",
    "year": "1874",
    "prcp": "0",
    "clr" : "dodgerblue",
    "map" : true,
    "val" : false,
    "ant" : "unknown",
    "yoff": 0,
  },
 
  {
    "idx" : 4,
    "name": "Loomis",
    "year": "1882",
    "prcp": "0",
    "clr" : "blueviolet",
    "map" : true,
    "val" : false,
    "ant" : "unknown",
    "yoff": 0,
  },

  {
    "idx" : 5,
    "name": "Murray",
    "year": "1887",
    "prcp": "843",
    "clr" : "blueviolet",
    "map" : true,
    "val" : true,
    "ant" : true,
    "yoff": 0,
  },
 
  {
    "idx" : 6,
    "name": "Brückner",
    "year": "1905",
    "prcp": "843",
    "clr" : "blueviolet",
    "map" : false,
    "val" : true,
    "ant" : true,
    "yoff": 0,
  },
 
  {
    "idx" : 7,
    "name": "Supan",
    "year": "1898",
    "prcp": "0",
    "clr" : "royalblue",
    "map" : true,
    "val" : false,
    "ant" : "unknown",
    "yoff": 0,
  },
 
  {
    "idx" : 8,
    "name": "Bezdek",
    "year": "1904",
    "prcp": "936",
    "clr" : "royalblue",
    "map" : false,
    "val" : true,
    "ant" : false,
    "yoff": 0,
  },
 
  {
    "idx" : 9,
    "name": "Fritsche",
    "year": "1906",
    "prcp": "765",
    "clr" : "royalblue",
    "map" : false,
    "val" : true,
    "ant" : true,
    "yoff": 0,
  },
 
  {
    "idx" : 10,
    "name": "Kerner",
    "year": "1907",
    "prcp": "815",
    "clr" : "royalblue",
    "map" : false,
    "val" : true,
    "ant" : false,
    "yoff": 0,
  },
 
  {
    "idx" : 11,
    "name": "Wüst",
    "year": "1922",
    "prcp": "753",
    "clr" : "royalblue",
    "map" : false,
    "val" : true,
    "ant" : true,
    "yoff": 0,
  },
 
  {
    "idx" : 12,
    "name": "Brooks & Hunt",
    "year": "1930",
    "prcp": "659",
    "clr" : "orange",
    "map" : false,
    "val" : true,
    "ant" : true,
    "yoff": 0,
  },
 
  {
    "idx" : 13,
    "name": "Meinardus",
    "year": "1934",
    "prcp": "665",
    "clr" : "orange",
    "map" : true,
    "val" : true,
    "ant" : "unknown",
    "yoff": 0,
  },
 
  {
    "idx" : 14,
    "name": "Möller",
    "year": "1951",
    "prcp": "670",
    "clr" : "orange",
    "map" : false,
    "val" : true,
    "ant" : "unknown",
    "yoff": 0,
  },
 
  {
    "idx" : 15,
    "name": "Drozdov",
    "year": "1939",
    "prcp": "0",
    "clr" : "gray",
    "map" : true,
    "val" : false,
    "ant" : "unknown",
    "yoff": 0,
  },
 
  {
    "idx" : 16,
    "name": "L'vovich",
    "year": "1970",
    "prcp": "730",
    "clr" : "gray",
    "map" : false,
    "val" : true,
    "ant" : "unknown",
    "yoff": 0,
  },
 
  {
    "idx" : 17,
    "name": "Kalinin",
    "year": "1971",
    "prcp": "730",
    "clr" : "gray",
    "map" : false,
    "val" : true,
    "ant" : true,
    "yoff": 0,
  },
 
  {
    "idx" : 18,
    "name": "Kuznetsova & Sharova",
    "year": "1964",
    "prcp": "725",
    "clr" : "green",
    "map" : true,
    "val" : true,
    "ant" : "unknown",
    "yoff": 0,
  },

  {
    "idx" : 19,
    "name": "Budyko",
    "year": "1977",
    "prcp": "730",
    "clr" : "green",
    "map" : false,
    "val" : true,
    "ant" : true,
    "yoff": 0,
  },
  
  {
    "idx" : 20,
    "name": "Lvovich",
    "year": "1979",
    "prcp": "762",
    "clr" : "green",
    "map" : false,
    "val" : true,
    "ant" : true,
    "yoff": 0,
  },
 
  {
    "idx" : 21,
    "name": "Geiger",
    "year": "1965",
    "prcp": "0",
    "clr" : "gold",
    "map" : true,
    "val" : false,
    "ant" : "unknown",
    "yoff": 0,
  },
 
  {
    "idx" : 22,
    "name": "Mather",
    "year": "1969",
    "prcp": "787",
    "clr" : "gold",
    "map" : false,
    "val" : true,
    "ant" : false,
    "yoff": 0,
  },
 
  {
    "idx" : 23,
    "name": "Legates",
    "year": "1987",
    "prcp": "820",
    "clr" : "gold",
    "map" : true,
    "val" : true,
    "ant" : true,
    "yoff": 0,
  },

  {
    "idx" : 24,
    "name": "Jaeger",
    "year": "1978",
    "prcp": "759",
    "clr" : "gold",
    "map" : false,
    "val" : true,
    "ant" : "unknown",
    "yoff": 0,
  },

  {
    "idx" : 25,
    "name": "Baumgartner & Reichel",
    "year": "1975",
    "prcp": "748",
    "clr" : "dodgerblue",
    "map" : true,
    "val" : true,
    "ant" : true,
    "yoff": 0,
  },
 
  {
    "idx" : 26,
    "name": "Bengtsson",
    "year": "2010",
    "prcp": "732",
    "clr" : "dodgerblue",
    "map" : false,
    "val" : true,
    "ant" : "unknown",
    "yoff": 0,
  },
 
  {
    "idx" : 27,
    "name": "Hartmann",
    "year": "2015",
    "prcp": "746",
    "clr" : "dodgerblue",
    "map" : false,
    "val" : true,
    "ant" : true,
    "yoff": 0,
  },
 
  {
    "idx" : 28,
    "name": "UNESCO",
    "year": "1978",
    "prcp": "800",
    "clr" : "tan",
    "map" : true,
    "val" : true,
    "ant" : true,
    "yoff": 0,
  },
 
  {
    "idx" : 29,
    "name": "Shiklomanov & Sokolov",
    "year": "1983",
    "prcp": "800",
    "clr" : "tan",
    "map" : false,
    "val" : true,
    "ant" : true,
    "yoff": 0,
  },
 
  {
    "idx" : 30,
    "name": "Shiklomanov",
    "year": "1998",
    "prcp": "800",
    "clr" : "tan",
    "map" : false,
    "val" : true,
    "ant" : true,
    "yoff": 0,
  },
 
  {
    "idx" : 31,
    "name": "Legates & Wilmott",
    "year": "1990",
    "prcp": "845",
    "clr" : "pink",
    "map" : true,
    "val" : true,
    "ant" : true,
    "yoff": 0,
  },
 
  {
    "idx" : 32,
    "name": "Legates & Mather",
    "year": "1992",
    "prcp": "777",
    "clr" : "pink",
    "map" : true,
    "val" : true,
    "ant" : true,
    "yoff": 0,
  },
 
  {
    "idx" : 33,
    "name": "Legates & McCabe",
    "year": "2005",
    "prcp": "845",
    "clr" : "pink",
    "map" : false,
    "val" : true,
    "ant" : true,
    "yoff": 0,
  },
 
  {
    "idx" : 34,
    "name": "GPCC",
    "year": "2014",
    "prcp": "786",
    "clr" : "goldenrod",
    "map" : true,
    "val" : true,
    "ant" : false,
    "yoff": 0,
  },
 
];

var nodeData = [
  { "src": 1, "des": 2, "xoff":  0, "yoff":  0, "ls": 0},
  { "src": 4, "des": 5, "xoff":  0, "yoff":  0, "ls": 0},
  { "src": 4, "des": 6, "xoff":0.3, "yoff":0.1, "ls": 0},
  { "src": 7, "des": 8, "xoff":  0, "yoff":  0, "ls": 0},
  { "src": 7, "des": 9, "xoff":  0, "yoff":  0, "ls": 0},
  { "src": 7, "des":10, "xoff":  0, "yoff":  0, "ls": 0},
  { "src": 9, "des":11, "xoff":  5, "yoff":0.3, "ls": 0},
  { "src":10, "des":11, "xoff":  0, "yoff":  0, "ls": 0},
  { "src":12, "des":13, "xoff":  0, "yoff":  0, "ls": 0},
  { "src":12, "des":14, "xoff":0.8, "yoff":0.1, "ls": 0},
  { "src":13, "des":14, "xoff":  0, "yoff":  0, "ls": 0},
  { "src":15, "des":16, "xoff":  0, "yoff":  0, "ls": 0},
  { "src":15, "des":17, "xoff":  0, "yoff":  0, "ls": 0},
  { "src":18, "des":19, "xoff":  0, "yoff":  0, "ls": 0},
  { "src":18, "des":20, "xoff":  0, "yoff":  0, "ls": 0},
  { "src":21, "des":22, "xoff":  0, "yoff":  0, "ls": 0},
  { "src":21, "des":24, "xoff":  0, "yoff":  0, "ls": 0},
  { "src":22, "des":23, "xoff":  0, "yoff":  0, "ls": 0},
  { "src":25, "des":26, "xoff":  0, "yoff":  0, "ls": 0},
  { "src":25, "des":27, "xoff":  0, "yoff":  0, "ls": 0},
  { "src":28, "des":29, "xoff":  0, "yoff":  0, "ls": 0},
  { "src":28, "des":30, "xoff":  0, "yoff":  0, "ls": 0},
  { "src":31, "des":32, "xoff":2.0, "yoff":  0, "ls": 0},
  { "src":31, "des":33, "xoff":3.5, "yoff":0.2, "ls": 0},
];
